version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    
    ports:
      - 8000:80
